defaultPlacement: end
enableVersioning: true
handle: sportskiRezultat
name: 'Sportski rezultat'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5da841b1-ca0d-46ff-8bb1-04d6c889ac54:
    enabledByDefault: true
    hasUrls: true
    template: sportski-rezultat/_entry
    uriFormat: 'sportski-rezultat/{slug}'
structure:
  maxLevels: null
  uid: 8cbc0e60-c364-4889-9914-22551a975025
type: structure
